version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mfl-scoring"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gjos7i7n8mbg"
s3_prefix = "mfl-scoring"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
