---
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CloudFormation template that contains a Lambda function behind an
  API Gateway that has two stages mapped to two Lambda aliases

Parameters:
  BuildBucket:
    Description: S3 bucket that holds the build artifacts
    Type: String
    Default: mfl-scoring-builds
  HostedZoneId:
    Description: Hosted zone id of the domain under which this app will be served
    Type: String
    Default: Z0291479D96D3UFQISZF
  SubDomain:
    Description: SubDomain for API Gateway API
    Type: String
    Default: 'mflcheck.timismydaddy.com'
  # ApiKeySecretArn:
  #   Description: ARN of the secret that holds the MFL API key
  #   Type: String
  #   Default: arn:aws:secretsmanager:us-east-1:287140326780:secret:MflScoringApiKeySecret-x1mDJYYsWop9-ugl5G0
  KmsKeyArn:
    Description: ARN of the KMS key used to encrypt the secret. It's here to avoid circular dependency hell.
    Type: String
    Default: arn:aws:kms:us-east-1:287140326780:key/mrk-be939ce79e1f4d538be08038d602da0f

Resources:
  MflScoringCertificate:
    Type: 'AWS::CertificateManager::Certificate'
    Properties:
      DomainName: !Ref SubDomain
      CertificateTransparencyLoggingPreference: DISABLED
      ValidationMethod: DNS

  MflScoringCustomDomain:
    Type: AWS::ApiGatewayV2::DomainName
    Properties: 
      DomainName: !Ref SubDomain
      DomainNameConfigurations:
        - CertificateArn: !Ref MflScoringCertificate

  MflScoringApiMapping:
    DependsOn:
         - MflScoringRecordSet
    Type: "AWS::ApiGatewayV2::ApiMapping"
    Properties:
      DomainName: !Ref SubDomain
      ApiId: !Ref MflScoringApi
      Stage: !Ref MflScoringApiStageProd
      ApiMappingKey: ''

  MflScoringRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref SubDomain
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt MflScoringCustomDomain.RegionalHostedZoneId
        DNSName: !GetAtt MflScoringCustomDomain.RegionalDomainName

  MflScoringFunction:
    Type: AWS::Lambda::Function
    Properties:
      Role:
        Fn::GetAtt:
        - MflScoringStagedFunctionIamRole
        - Arn
      Code: 
        S3Bucket: !Sub ${BuildBucket}
        S3Key: builds/bootstrap.zip
        # S3ObjectVersion: TODO
      Handler: bootstrap
      Runtime: provided.al2
      MemorySize: 128
      Timeout: 5

  MflScoringStagedFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: secretsManager
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:DescribeSecret
                  - secretsmanager:GetSecretValue
                Resource: !ImportValue mfl-scoring-MflScoringApiKeySecretArn #!Ref ApiKeySecretArn
        - PolicyName: kmsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - 'kms:DescribeKey'
                - 'kms:Encrypt'
                - 'kms:Decrypt'
                - 'kms:ReEncrypt*'
                - 'kms:GenerateDataKey'
                - 'kms:GenerateDataKeyWithoutPlaintext'
                Resource: !Ref KmsKeyArn
        - PolicyName: ssmAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: ssm:GetParameter
                Resource: arn:aws:ssm:us-east-1:287140326780:parameter/MFL_API_KEY

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !GetAtt MflScoringFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 
          - "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${MflScoringApi}:*/*"
          - MflScoringApi: !Ref MflScoringApi

  MflScoringApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: MFL Scoring API
      ProtocolType: HTTP

  MflScoringIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref MflScoringApi
      Description: Lambda proxy integration
      IntegrationType: AWS_PROXY
      IntegrationMethod: POST
      PayloadFormatVersion: "2.0"
      IntegrationUri: !Join
        - ''
        - - !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:${MflScoringFunction}'
          - ':${stageVariables.LambdaAlias}/invocations'

  MflScoringApiRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref MflScoringApi
      RouteKey: "GET /mfl-scoring"
      Target: !Join
        - /
        - - integrations
          - !Ref MflScoringIntegration

  MflScoringFunctionStagePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Ref MflScoringFunctionStageAlias
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:"
          - !Ref MflScoringApi
          - "/*/*/*"

  MflScoringFunctionProdPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:invokeFunction
      FunctionName: !Ref MflScoringFunctionProdAlias
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:"
          - !Ref MflScoringApi
          - "/*/*/*"

  MflScoringFunctionStageAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName:
        Ref: MflScoringFunction
      FunctionVersion: $LATEST
      Name: STAGE
      
  MflScoringFunctionProdAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref MflScoringFunction
      FunctionVersion: 1
      Name: PROD

  MflScoringApiStageStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: MflScoringApi
      AccessLogSettings:
        DestinationArn: !GetAtt MflScoringStageStageLogGroup.Arn
        Format: >
          $context.identity.sourceIp - - [$context.requestTime] "$context.httpMethod $context.routeKey $context.protocol" 
          $context.status $context.responseLength $context.requestId $context.integrationErrorMessage
      DefaultRouteSettings:
        DetailedMetricsEnabled: True
      StageName: stage
      StageVariables:
        LambdaAlias: STAGE
      AutoDeploy: true

  MflScoringApiStageProd:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: MflScoringApi
      DefaultRouteSettings:
        DetailedMetricsEnabled: True
      StageName: prod
      StageVariables:
        LambdaAlias: PROD
      AutoDeploy: true

  MflScoringStageStageLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub 
          - 'API-Gateway-Execution-Logs_${ApiId}/stage'
          - ApiId: !Ref MflScoringApi
      RetentionInDays: 30

  MflScoringStageProdLogGroup:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub 
          - 'API-Gateway-Execution-Logs_${ApiId}/prod'
          - ApiId: !Ref MflScoringApi
      RetentionInDays: 30

Outputs:
  StageUrl:
    Description: URL of the "stage" stage
    Value: !Sub 
      - "https://${MflScoringApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/mfl-scoring"
      - Stage: !Ref MflScoringApiStageStage
  ProdUrl:
    Description: URL of the "prod" stage
    Value: !Sub 
      - "https://${MflScoringApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/mfl-scoring"
      - Stage: !Ref MflScoringApiStageProd
  CustomProdUrl:
    Description: Custom prod URL
    Value: !Join
      - ''
      - - "https://"
        - !Ref MflScoringCustomDomain
        - "/mfl-scoring"
  MflScoringFunctionArn:
    Value: !GetAtt MflScoringFunction.Arn
    Export:
      Name: MflScoringFunctionCheckArn