AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mfl-scoring
  
  Sample SAM Template for mfl-scoring

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  MflScoringFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      Role: !GetAtt MflScoringFunctionIamRole.Arn
      CodeUri: mfl-scoring/
      Handler: mfl-scoring
      #Runtime: provided.al2
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /mfl-scoring
            Method: GET
      Environment: 
        Variables:
          MFL_API_KEY: "{{resolve:ssm:MFL_API_KEY:1}}"

  MflScoringFunctionIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
      - PolicyName: kmsAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - kms:Decrypt
            Resource: "*"
      - PolicyName: ssmAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ssm:GetParameter
            Resource:
            - arn:aws:ssm:us-east-1:287140326780:parameter/MFL_API_KEY

Outputs:
  MflScoringAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mfl-scoring/"
  MflScoringFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt MflScoringFunction.Arn
  #MflScoringFunctionIamRole:
  #  Description: "Implicit IAM Role created for the MflScoringFunction"
  #  Value: !GetAtt MflScoringFunctionRole.Arn
