AWSTemplateFormatVersion: 2010-09-09
Description: |
  ACFS3 - S3 Static site with CF and ACM
  Adopted From: https://github.com/aws-samples/amazon-cloudfront-secure-static-site
  (uksb-1qnk6ni7b) (version:v0.5)

Rules:
  OnlyUsEast1:
    Assertions:
      - Assert:
          Fn::Equals:
            - !Ref AWS::Region
            - us-east-1
        AssertDescription: |
          This template can only be deployed in the us-east-1 region.
          This is because the ACM Certificate must be created in us-east-1

Conditions:
  CreateApexConfig: !Equals
    - !Ref CreateApex
    - 'yes'

Parameters:
  SubDomain:
    Description: The part of a website address before your DomainName - e.g. www or img
    Type: String
    Default: mfl
    AllowedPattern: ^[^.]*$
  DomainName:
    Description: The part of a website address after your SubDomain - e.g. example.com
    Type: String
    Default: timkelsch.com
  HostedZoneId:
    Description: HostedZoneId for the domain e.g. Z23ABC4XYZL05B
    Type: String
    Default: Z07419102HFRMCTH28NVX
  CreateApex:
    Description: Create an Apex Alias in CloudFront distribution - yes/no
    Type: String
    Default: 'no'
    AllowedValues: ['yes', 'no']
  S3BucketLogsName:
    Description: Logging Bucket
    Type: String
    Default: !Sub "${SubDomain}.${DomainName}-logs"
  # S3BucketLogs:
  #   Description: Logging Bucket
  #   Type: String
  # S3BucketRoot:
  #   Description: Content Bucket
  #   Type: String
  #   Default: !Sub "${SubDomain}.${DomainName}"
  # S3BucketRootName:
  #   Description: Content Bucket
  #   Type: String
  # S3BucketRootArn:
  #   Description: Content Bucket locator
  #   Type: String

Resources:
  MflScoringWebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${SubDomain}.${DomainName}'
      WebsiteConfiguration:
           IndexDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '${SubDomain}.${DomainName}'
      SubjectAlternativeNames:
        Fn::If:
          - CreateApexConfig
          - - Ref: DomainName
          - Ref: AWS::NoValue
      DomainValidationOptions:
        - DomainName: !Sub '${SubDomain}.${DomainName}'
          HostedZoneId: !Ref HostedZoneId
        - Fn::If:
            - CreateApexConfig
            - DomainName: !Ref DomainName
              HostedZoneId: !Ref HostedZoneId
            - Ref: AWS::NoValue
      ValidationMethod: DNS

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Sub '${SubDomain}.${DomainName}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: s3:GetObject
            Principal:
              Service: 'cloudfront.amazonaws.com'
            Effect: Allow
            Resource: !Join [ '', [ 'arn:aws:s3:::', !Ref MflScoringWebsiteBucket, '/*' ] ]
            Condition:
              StringEquals:
                'AWS:SourceArn': !Sub 'arn:${AWS::Partition}:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub '${SubDomain}.${DomainName}'
          - !If [CreateApexConfig, !Ref DomainName, !Ref 'AWS::NoValue']
        DefaultCacheBehavior:
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            TargetOriginId: !Sub 'S3-${SubDomain}.${DomainName}-root'
            ViewerProtocolPolicy: 'redirect-to-https'
        CustomErrorResponses:
          - ErrorCachingMinTTL: 60
            ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: '/404.html'
          - ErrorCachingMinTTL: 60
            ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: '/403.html'
        Enabled: true
        HttpVersion: 'http2'
        DefaultRootObject: 'index.html'
        IPV6Enabled: false
        Logging:
          Bucket: !Ref 'S3BucketLogsName'
          IncludeCookies: false
          Prefix: 'cdn/'
        Origins:
          #- DomainName: !Sub '${SubDomain}.${DomainName}.s3-website-us-east-1.amazonaws.com'
          - DomainName: !GetAtt MflScoringWebsiteBucket.DomainName
            Id: !Sub 'S3-${SubDomain}.${DomainName}-root'
            OriginAccessControlId: !Ref OriginAccessControl
            S3OriginConfig: {}
        PriceClass: 'PriceClass_100'
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: 'TLSv1.2_2021'
          SslSupportMethod: 'sni-only'
      Tags:
        - Key: Solution
          Value: ACFS3

  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        # Get a unique ID for the OAC Config name.
        # Name must be unique within account
        Name: !Sub
          - amzn-secure-static-site-${guid}
          - guid: !Sub '${SubDomain}.${DomainName}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      RecordSets:
        - Name: !Sub '${SubDomain}.${DomainName}'
          Type: 'A'
          AliasTarget:
            DNSName: !GetAtt 'CloudFrontDistribution.DomainName'
            EvaluateTargetHealth: false
            # The  following HosteZoneId is always used for alias records pointing to CF.
            HostedZoneId: 'Z2FDTNDATAQYW2'

  ApexRoute53RecordSetGroup:
    Condition: CreateApexConfig
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub '${DomainName}.'
      RecordSets:
        - Name: !Ref 'DomainName'
          Type: 'A'
          AliasTarget:
            DNSName: !GetAtt 'CloudFrontDistribution.DomainName'
            EvaluateTargetHealth: false
            # The  following HosteZoneId is always used for alias records pointing to CF.
            HostedZoneId: 'Z2FDTNDATAQYW2'

  ResponseHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: 'static-site-security-headers'
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 63072000
            IncludeSubdomains: true
            Override: true
            Preload: true
          ContentSecurityPolicy:
            ContentSecurityPolicy: connect-src https://3xi97uokw5.execute-api.us-east-1.amazonaws.com; style-src https://fonts.googleapis.com https://fonts.gstatic.com 'self'; font-src https://fonts.googleapis.com https://fonts.gstatic.com 'self'; default-src 'none'; img-src 'self'; script-src 'self';
            Override: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: 'same-origin'
            Override: true
          XSSProtection:
            ModeBlock: true
            Override: true
            Protection: true

Outputs:
  # S3BucketLogs:
  #   Description: Logging bucket
  #   Value: !GetAtt CustomResourceStack.Outputs.S3BucketLogs
  S3BucketRoot:
    Description: Website bucket
    Value: !GetAtt MflScoringWebsiteBucket.Arn
  S3BucketLogsName:
    Description: Logging bucket name
    Value: !GetAtt CustomResourceStack.Outputs.S3BucketLogsName
  S3BucketRootName:
    Description: Website bucket name
    Value: !Ref MflScoringWebsiteBucket
  # CertificateArn:
  #   Description: Issued certificate
  #   Value: !GetAtt AcmCertificateStack.Outputs.CertificateArn
  # CFDistributionName:
  #   Description: CloudFront distribution
  #   Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDistribution
  # CloudFrontDomainName:
  #   Description: Website address
  #   Value: !GetAtt CloudFrontStack.Outputs.CloudFrontDomainName
  # CloudFrontDistribution:
  #   Description: CloudFront distribution
  #   Value: !GetAtt CloudFrontDistribution.DomainName