name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

defaults:
  run:
    working-directory: ./mfl-scoring
    shell: bash

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.3"
          cache: false

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
            sh -s -- -b $(go env GOPATH)/bin v1.62.0

      - name: Run tests
        run: go test -cover ./...

      - name: Run linting
        run: golangci-lint run -v -c ../.golangci.yml .

  build-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (validation only)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: mfl-scoring-image:validation
